
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 09 13:00:45 BRT 2019
//----------------------------------------------------

package br.edu.ifb.compiladores.sintatico;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int PRNT = 8;
  public static final int CHAR = 35;
  public static final int CHAVE_E = 30;
  public static final int CHAVE_D = 29;
  public static final int CHAR_T = 7;
  public static final int DIFERENTE = 21;
  public static final int VIRGULA = 31;
  public static final int SETOP = 12;
  public static final int NOT = 13;
  public static final int AND = 14;
  public static final int IGUAL = 20;
  public static final int OR = 15;
  public static final int DIV = 25;
  public static final int IF = 2;
  public static final int ID = 37;
  public static final int PORCENTO = 26;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int PONTO_VIRGULA = 32;
  public static final int MAIOR = 18;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int ADD = 22;
  public static final int MENOR = 16;
  public static final int VOID = 36;
  public static final int INTEIRO_T = 9;
  public static final int ELSE = 3;
  public static final int INTEIRO = 33;
  public static final int WHILE = 4;
  public static final int PARENTESE_E = 28;
  public static final int PARENTESE_D = 27;
  public static final int FLOAT = 34;
  public static final int FLOAT_T = 6;
  public static final int PROC = 10;
  public static final int MENOR_IGUAL = 17;
  public static final int SUB = 23;
  public static final int MAIOR_IGUAL = 19;
  public static final int VAR = 11;

  public static final String[] terminalNames = new String[] {
          "EOF",
          "error",
          "IF",
          "ELSE",
          "WHILE",
          "RETURN",
          "FLOAT_T",
          "CHAR_T",
          "PRNT",
          "INTEIRO_T",
          "PROC",
          "VAR",
          "SETOP",
          "NOT",
          "AND",
          "OR",
          "MENOR",
          "MENOR_IGUAL",
          "MAIOR",
          "MAIOR_IGUAL",
          "IGUAL",
          "DIFERENTE",
          "ADD",
          "SUB",
          "MUL",
          "DIV",
          "PORCENTO",
          "PARENTESE_D",
          "PARENTESE_E",
          "CHAVE_D",
          "CHAVE_E",
          "VIRGULA",
          "PONTO_VIRGULA",
          "INTEIRO",
          "FLOAT",
          "CHAR",
          "VOID",
          "ID"
  };
}

